### ISSUE TITLE
Exposing with a custom URL

### ISSUE THREAD

**Issue by koltyakov** [codecov/self-hosted#12]
Hi and thank you for going OpenSourcing your wonderful product!

I'm trying to lift a POC exposing is via an external URL through ngrok.

```bash
ngrok http 8080
```

![image](https://github.com/codecov/self-hosted/assets/7816483/325935b8-4a4a-49ea-b64f-b1cbd0fc3f90)

```yml
# ./config/codecov.yml
setup:
  codecov_url: https://a-custom-url-through-ngrok.ngrok-free.app
# with other configurations/license/github app/etc applied
```

```yml
# ./docker-compose.yml
# default one including:
  frontend:
    image: codecov/enterprise-frontend:latest-stable
    environment:
      - CODECOV_BASE_HOST=localhost:8080
      - CODECOV_API_HOST=localhost:8080
      - CODECOV_IA_HOST=localhost:8080
      - CODECOV_SCHEME=http
    volumes:
      - ./config:/config
    ports:
      - "8080"
    networks:
      - codecov
```

When I'm reaching the URL I'm getting the loading screen (with umbrella animation) and the following errors:

![image](https://github.com/codecov/self-hosted/assets/7816483/2aeba2b2-f423-4343-93a2-84943b5138a4)

So even while having `codecov_url` provided due something else some calls are sent to `http://localhost:8080`, if to modify `CODECOV_` env vars in `frontend` in the docker compose the error is exactly the same with same 8080 port.

I can't see anything but [/docs/configuration#codecov-url](https://docs.codecov.com/docs/configuration#codecov-url) regarding providing a custom URL. Am I missing something obvious?

**Comment by fmdoe** [comment]
I had to change the environment variables to something like this:
```yml
  frontend:
    image: codecov/enterprise-frontend:latest-stable
    environment:
      - CODECOV_BASE_HOST=a-custom-url-through-ngrok.ngrok-free.app
      - CODECOV_API_HOST=a-custom-url-through-ngrok.ngrok-free.app
      - CODECOV_IA_HOST=a-custom-url-through-ngrok.ngrok-free.app
      - CODECOV_SCHEME=https
```
