### ISSUE TITLE
Frontend container forces to call API at `http://localhost:8080`

### ISSUE THREAD

**Issue by aldy505** [codecov/self-hosted#3]
Hello there! I know that this has just became public like a few hours ago, but I'm super excited and curious to run Codecov on my end.

As the title stated, the frontend container calls `http://localhost:8080` as the API host, with whatever configuration I put on `docker-compose.yml` or `config/codecov.yml` file.

![image](https://github.com/codecov/self-hosted/assets/7274326/23ec5a3c-c304-4ecb-9aae-ebeb72e0cc1c)

My `docker-compose.yml` file is:

```yaml
services:
  gateway:
    image: codecov/enterprise-gateway:${CODECOV_VERSION} #note: this is for setup purposes only, be sure to pin to the latest release from our changelog: https://docs.codecov.io/changelog
    volumes:
      - ./config:/config
      #- ${CODECOV_SSL_CERT-/cert/codecov.crt}:/etc/codecov/ssl/certs/cert.crt:ro # uncomment if using ssl
    ports:
      - "${CODECOV_PORT-127.0.0.1:8080}:8080"
      #- "${CODECOV_SSL_PORT-8443}:8443" # uncomment if using ssl
    environment:
      - CODECOV_GATEWAY_MINIO_ENABLED=true
      #- CODECOV_GATEWAY_SSL_ENABLED=true # uncomment if using ssl
    networks:
      - codecov
    depends_on:
      - api
      - frontend

  frontend:
    image: codecov/enterprise-frontend:${CODECOV_VERSION} #note: this is for setup purposes only, be sure to pin to the latest release from our changelog: https://docs.codecov.io/changelog
    environment:
      - CODECOV_BASE_HOST=${CODECOV_PUBLIC_HOST}
      - CODECOV_API_HOST=${CODECOV_PUBLIC_HOST}
      - CODECOV_IA_HOST=${CODECOV_PUBLIC_HOST}
      - CODECOV_SCHEME=http
      - CODECOV_FRONTEND_IPV6_DISABLED=true
    volumes:
      - ./config:/config
    #ports:
    #  - "8080"
    networks:
      - codecov
```

With `CODECOV_PUBLIC_HOST` set to `172.31.2.44`, `CODECOV_PORT` also set to `172.31.2.44:8080` (tried to set it to `172.31.2.44:80` and it still behaves the same way), and `CODECOV_VERSION` to `v5.0.1`.

Thank you! Looking forward to the future of Codecov.
