### ISSUE TITLE
How to troubleshoot gh app connection issues?

### ISSUE THREAD

**Issue by kwonoj** [codecov/self-hosted#50]
After trying self hosted installation guide, I'm still seeing 

<img width="717" alt="Image" src="https://github.com/user-attachments/assets/8e995c70-5f22-45ba-8e97-1c66fe557b7f" />

and commit / pr information is not displayed in codecov instance + codecov cannot comment to PRs.

Peeking logs, it looks like instance cannot reach gh app installation correctly even after uninstall / reinstall multiple times. Confirmed webhook events are handled correctly in api logs. Any tips / suggestions how to troubleshoot, debug this?

```
{"message": "Getting owner's GitHub Apps info", "asctime": "2025-01-07 06:25:50,367", "name": "shared.bots.github_apps", "levelname": "INFO", "lineno": 277, "pathname": "/usr/local/lib/python3.13/site-packages/shared/bots/github_apps.py", "funcName": "get_github_app_info_for_owner", "threadName": "MainThread", "taskName": null, "installation_name": "codecov_app_installation", "ownerid": 1, "repoid": 214, "context": {"task_name": "app.tasks.upload.PreProcessUpload", "task_id": "711909c1-bbfa-42c3-8538-087ab532cf28", "owner_username": "redacted", "owner_service": "github", "owner_plan": "users-basic", "owner_id": 1, "repo_name": "redacted-Web", "repo_id": 214, "commit_sha": "6a6d3c3b3bc40ab770a240cb6afd30dbbfb8f38d", "commit_id": null, "sentry_trace_id": null}, "logger.name": "shared.bots.github_apps", "logger.thread_name": "MainThread", "level": "INFO"}
{"message": "Get repo appropriate bot token", "asctime": "2025-01-07 06:25:50,371", "name": "shared.bots.repo_bots", "levelname": "INFO", "lineno": 55, "pathname": "/usr/local/lib/python3.13/site-packages/shared/bots/repo_bots.py", "funcName": "get_repo_appropriate_bot_token", "threadName": "MainThread", "taskName": null, "installation_info": null, "repoid": 214, "is_private": true, "service": "github", "context": {"task_name": "app.tasks.upload.PreProcessUpload", "task_id": "711909c1-bbfa-42c3-8538-087ab532cf28", "owner_username": "redacted", "owner_service": "github", "owner_plan": "users-basic", "owner_id": 1, "repo_name": "redacted-Web", "repo_id": 214, "commit_sha": "6a6d3c3b3bc40ab770a240cb6afd30dbbfb8f38d", "commit_id": null, "sentry_trace_id": null}, "logger.name": "shared.bots.repo_bots", "logger.thread_name": "MainThread", "level": "INFO"}
{"message": "Unable to reach git provider because repo doesn't have a valid bot", "asctime": "2025-01-07 06:25:50,378", "name": "tasks.preprocess_upload", "levelname": "WARNING", "lineno": 142, "pathname": "/worker/tasks/preprocess_upload.py", "funcName": "get_repo_service", "threadName": "MainThread", "taskName": null, "repoid": 214, "commit": "6a6d3c3b3bc40ab770a240cb6afd30dbbfb8f38d", "context": {"task_name": "app.tasks.upload.PreProcessUpload", "task_id": "711909c1-bbfa-42c3-8538-087ab532cf28", "owner_username": "redacted", "owner_service": "github", "owner_plan": "users-basic", "owner_id": 1, "repo_name": "redacted-Web", "repo_id": 214, "commit_sha": "6a6d3c3b3bc40ab770a240cb6afd30dbbfb8f38d", "commit_id": null, "sentry_trace_id": null}, "logger.name": "tasks.preprocess_upload", "logger.thread_name": "MainThread", "level": "WARNING"}
```

// config

```
setup:
    codecov_url: https://[redacted].com
    enterprise_license: "somevalue"
    admins:
        service: github
        # This user does not have admin, corp security policy does not allow permanent admin user
        username: "someuser"
    http:
        cookie_secret: "somesecret"
        cookies_domain: [redacted].com
    timeseries:
        enabled: false
github:
    global_upload_token: "sometoken"
    client_id: "someid"
    client_secret: "somesecret"
    webhook_secret: "somesecret"
    integration:
        id: someid
        pem: /github_config/file.pem
github_enterprise:
    client_id: "someid"
    client_secret: "somesecret"
    global_upload_token: "sometoken"
    webhook_secret: "somesecret"
    integration:
        id: someid
        pem: /github_config/file.pem
services:
    _extend: true
    minio:
        host: s3.amazonaws.com
        bucket: somebucket
        region: someregion
        verify_ssl: true
        port: 443
        iam_auth: true
```
