### ISSUE TITLE
Cannot Upload to s3

### ISSUE THREAD

**Issue by isatfg** [codecov/self-hosted#59]
Hi

I have a self hosted codecov running however the report cannot be uploaded to s3. I have tried using the codecov cli as well as a github action.  I get an error in the api InvalidAccessKeyId even though the access is valid. I have test the access key and I am able to upload to the bucket using the access key.

```
  setup:
...
  minio:
     host: "s3.amazonaws.com"
     bucket: "xx"
     region: "eu-west-1"
     verify_ssl: true
     port: 443
     access_key_id: 'XX'
     secret_access_key: 'XX'
```

`
response_error\nminio.error.S3Error: S3 operation failed; code: InvalidAccessKeyId, message: The AWS Access Key Id you provided does not exist in our records., resource: None, request_id: xxx, host_id: xxx=", "taskName": null, "status_code": 500, "request": "<WSGIRequest: POST '/upload/github/xx-`
