### ISSUE TITLE
Missing Comments

### ISSUE THREAD

**Issue by isatfg** [codecov/self-hosted#60]
Hi 

I have codecov selfhosted running on EKS. I am able to login fine and the report is being uploaded successfully. The issue I'm facing it there are no comments being added to my PR. 

here is my codecov.yaml which is mounted /config/codecov.yaml

```
setup:
  codecov_url: mydomain.com
  enterprise_license: "xxxx.."
  admins:
    - service: github
      username: "user1"
    - service: github
      username: "user2"
    - service: github
      username: "user3"
    - service: github
      username: "user4"      
  http:
    cookie_secret: "xxxxxxxxxx"
    cookies_domain: mydomain.com
  timeseries:
    enabled: true
site:
  comment:
    # I added this recently but still does not add comments 
    layout: "reach,diff,flags,tree"
github:
  organizations:
    - "xxxxxxxxx"
  client_id: "xxxxxxxxxxxxxxxxxxxx"
  client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  global_upload_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  webhook_secret: "xxxxxxxxxxxxxxxxxxxxxx"
  integration:
    id: "xxxxxxx"
    pem: "/config/file.pem"

services:
  redis_url: "redis://codecov-redis-master.tools.svc.cluster.local:6379"
  database_url: "postgres://xxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxq@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:5432/codecov"
  timeseries_database_url: "postgres://xxxxxxxx:xxxxxxxxxxxx@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:5432/postgres"
  minio:
    host: 's3.amazonaws.com'
    bucket: 'xxxxxxxxxxxxxxxxxxxx'
    region: 'eu-west-1'
    verify_ssl: true
    port: 443
    access_key_id: 'xxxxxxxxxxxxxxxxxxxx'
    secret_access_key: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

```

I do see an error in the logs when I create a PR
```

codecov-worker-6c598db94d-gzs4n codecov-worker {"message": "Get repo appropriate bot token", "asctime": "2025-04-15 10:09:30,491", "name": "shared.bots.repo_bots", "levelname": "INFO", "lineno": 55, "pathname": "/usr/local/lib/python3.13/site-packages/shared/bots/repo_bots.py", "funcName": "get_repo_appropriate_bot_token", "threadName": "MainThread", "taskName": null, "installation_info": null, "repoid": xxx, "is_private": true, "service": "github", "context": {"task_name": "app.tasks.pulls.Sync", "task_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, "owner_username": "xxxxxxxx", "owner_service": "github", "owner_plan": "users-developer", "owner_id": x, "repo_name": "xxxxxxxx", "repo_id": xxx, "commit_sha": null, "commit_id": null, "sentry_trace_id": null}, "logger.name": "shared.bots.repo_bots", "logger.thread_name": "MainThread", "level": "INFO"}
codecov-worker-6c598db94d-gzs4n codecov-worker {"message": "Could not sync pull because there is no valid bot found for that repo", "asctime": "2025-04-15 10:09:30,491", "name": "tasks.sync_pull", "levelname": "WARNING", "lineno": 127, "pathname": "/worker/tasks/sync_pull.py", "funcName": "run_impl_within_lock", "threadName": "MainThread", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.13/site-packages/shared/bots/repo_bots.py\", line 41, in get_repo_appropriate_bot\n    return get_owner_or_appropriate_bot(\n        DjangoSQLAlchemyRepositoryWrapper.get_repo_owner(repo)\n    )\n  File \"/usr/local/lib/python3.13/site-packages/shared/bots/owner_bots.py\", line 29, in get_owner_or_appropriate_bot\n    raise OwnerWithoutValidBotError()\nshared.bots.exceptions.OwnerWithoutValidBotError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/worker/tasks/sync_pull.py\", line 123, in run_impl_within_lock\n    repository_service = get_repo_provider_service(\n        repository, installation_name_to_use=installation_name_to_use\n    )\n  File \"/usr/local/lib/python3.13/site-packages/sentry_sdk/tracing_utils.py\", line 673, in func_with_tracing\n    return func(*args, **kwargs)\n  File \"/worker/services/repository.py\", line 49, in get_repo_provider_service\n    adapter_auth_info = get_adapter_auth_information(\n        repository.owner,\n        repository=repository,\n        installation_name_to_use=installation_name_to_use,\n    )\n  File \"/usr/local/lib/python3.13/site-packages/shared/bots/__init__.py\", line 52, in get_adapter_auth_information\n    token, token_owner = get_repo_appropriate_bot_token(\n                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n        repository, installation_info\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/shared/bots/repo_bots.py\", line 79, in get_repo_appropriate_bot_token\n    raise e\n  File \"/usr/local/lib/python3.13/site-packages/shared/bots/repo_bots.py\", line 72, in get_repo_appropriate_bot_token\n    token_dict, appropriate_bot = get_repo_particular_bot_token(repo)\n                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"/usr/local/lib/python3.13/site-packages/shared/bots/repo_bots.py\", line 26, in get_repo_particular_bot_token\n    appropriate_bot = get_repo_appropriate_bot(repo)\n  File \"/usr/local/lib/python3.13/site-packages/shared/bots/repo_bots.py\", line 45, in get_repo_appropriate_bot\n    raise RepositoryWithoutValidBotError()\nshared.bots.exceptions.RepositoryWithoutValidBotError", "taskName": null, "pullid": 40, "repoid": xxx, "context": {"task_name": "app.tasks.pulls.Sync", "task_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "owner_username": "xxxxxxxx", "owner_service": "github", "owner_plan": "users-developer", "owner_id": x, "repo_name": "xxxxxxxx", "repo_id": xxx, "commit_sha": null, "commit_id": null, "sentry_trace_id": null}, "logger.name": "tasks.sync_pull", "logger.thread_name": "MainThread", "level": "WARNING"}
codecov-worker-6c598db94d-gzs4n codecov-worker {"message": "Task app.tasks.pulls.Sync[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx] succeeded in 0.042384403001051396s: {'notifier_called': False, 'commit_updates_done': {'merged_count': 0, 'soft_deleted_count': 0}, 'pull_updated': False, 'reason': 'no_bot'}", "asctime": "2025-04-15 10:09:30,520", "name": "celery.app.trace", "levelname": "INFO", "lineno": 131, "pathname": "/usr/local/lib/python3.13/site-packages/celery/app/trace.py", "funcName": "info", "threadName": "MainThread", "taskName": null, "data": {"id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "name": "app.tasks.pulls.Sync", "return_value": "{'notifier_called': False, 'commit_updates_done': {'merged_count': 0, 'soft_deleted_count': 0}, 'pull_updated': False, 'reason': 'no_bot'}", "runtime": 0.042384403001051396, "args": "()", "kwargs": "{'repoid': xxx, 'pullid': xx}"}, "context": {"task_name": "app.tasks.pulls.Sync", "task_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "owner_username": "xxxxxxxx", "owner_service": "github", "owner_plan": "users-developer", "owner_id": 1, "repo_name": "xxxxxxxx", "repo_id": xxx, "commit_sha": null, "commit_id": null, "sentry_trace_id": null}, "logger.name": "celery.app.trace", "logger.thread_name": "MainThread", "level": "INFO"}
```

I have double check my github app permissions and it matches the doc 100%
